### ISSUE TITLE
Error: loadLibrary failed: 0x0000007e

### ISSUE THREAD

**Issue by Evyatar108** [StackOverflowExcept1on/net-core-injector#1]
Hey, I'm getting an error when I try the .\_run.bat:

D:\ExtRepos\net-core-injector>.\_run.bat

D:\ExtRepos\net-core-injector>start DemoApplication\dist\DemoApplication.exe

D:\ExtRepos\net-core-injector>npm start -- inject DemoApplication.exe Bootstrapper\build\Release\Bootstrapper.dll RuntimePatcher\dist\RuntimePatcher.runtimeconfig.json RuntimePatcher\dist\RuntimePatcher.dll "RuntimePatcher.Main, RuntimePatcher" "InitializePatches"

> net-core-injector@1.0.0 start
> ts-node-esm src/main.ts inject DemoApplication.exe Bootstrapper\build\Release\Bootstrapper.dll RuntimePatcher\dist\RuntimePatcher.runtimeconfig.json RuntimePatcher\dist\RuntimePatcher.dll RuntimePatcher.Main, RuntimePatcher InitializePatches

net-core-injector inject <process_name> <bootstrapper> <runtime_config_path> <as
sembly_path> <type_name> <method_name>

inject C# library into process

Positionals:
  process_name                                               [string] [required]
  bootstrapper                                               [string] [required]
  runtime_config_path                                        [string] [required]
  assembly_path                                              [string] [required]
  type_name                                                  [string] [required]
  method_name                                                [string] [required]

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]

Error: loadLibrary failed: 0x0000007e
    at value (frida/runtime/core.js:229)
    at inject (/script1.js:4)
    at apply (native)
    at <anonymous> (frida/runtime/message-dispatcher.js:13)
    at c (frida/runtime/message-dispatcher.js:23) {
  fileName: 'frida/runtime/core.js',
  lineNumber: 229
}

**Comment by StackOverflowExcept1on** [comment]
You probably forgot to build the native library called `Bootstrapper`
